version: 2

updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "main"
    open-pull-requests-limit: 0

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "main"
    open-pull-requests-limit: 0

  - package-ecosystem: "pip"
    directory: "/conda/nlpsandbox"
    schedule:
      interval: "monthly"
    target-branch: "main"
    open-pull-requests-limit: 0
